name: GEDS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  geds:
    name: Test Against GEDS
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14.2
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14.2
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - run: whereis go
      - run: sudo apt-get install tree
      - run: tree

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
          fi

      - name: clone geds
        run: git clonehttps://github.com/GlobalEmpire/GERT test/GERT


      - name: Run Makefile
        run: make debug
        working-directory: test/GERT/GERTe

      - name: Create Resolutions
        run: go run test/create_resolutions.go
        env:
          ADDR1: 1123.1456
          ADDR2: 2345.1456
          KEY1: aaaaaaaaaaaaaaaaaaaa
          KEY2: aaaaaaaaaaaaaaaaaaaa

      - name: List Files
        run: ls -a test/GERT/GERTe


      - name: Start GEDS
        run: ./GERT/GERTe/GEDSv1.1d -a 0.0.0.0 -d &
        working-directory: test/

      - name: List Files
        run: ls -a test
      - run: tree

      - name: Wait / Sleep
        uses: jakejarvis/wait-action@v0.1.0
        with:
          time: '10s'


      - name: Run Basic Example
        run: go run examples/basic/parallel_starter/main.go
        env:
          PATH: /opt/hostedtoolcache/go/1.14.2/x64/bin/go
          CMD1: go run examples/basic/requester/main.go
          CMD2: go run examples/basic/target/main.go
          SERVER_ADDR: localhost:43780
          ADDR: 1123.1456
          TARGET_ADDR: 2345.1456
          KEY: aaaaaaaaaaaaaaaaaaaa



