name: Release

on:
  push:
    tags:
      - v*

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.14.2
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14.2
        id: go

      - name: Go Get
        run: go get github.com/OmegaRogue/gerte-go@latest
